class CreateInboundOrdersAndLogs < ActiveRecord::Migration[5.0]
  def change
    create_table :inbound_orders do |t|
      t.text :notes

      t.timestamps
    end

    create_table :inbound_logs do |t|
      t.references :inbound_order, null: false, foreign_key: true
      t.references :product, null: false, foreign_key: true
      t.jsonb :properties, null: false, default: {}
      t.integer :quantity, null: false
      t.references :shelf, null: true, foreign_key: true

      t.timestamps
    end

    # The InboundOrder transition model's table generated by statesman:
    create_table :inbound_order_transitions do |t|
      t.string :to_state, null: false
      t.jsonb :metadata, default: {}
      t.integer :sort_key, null: false
      t.integer :inbound_order_id, null: false
      t.boolean :most_recent, null: false
      t.timestamps null: false
    end

    add_index :inbound_order_transitions,
              [:inbound_order_id, :sort_key],
              unique: true,
              name: "index_inbound_order_transitions_parent_sort"

    add_index :inbound_order_transitions,
              [:inbound_order_id, :most_recent],
              unique: true,
              where: 'most_recent',
              name: "index_inbound_order_transitions_parent_most_recent"
  end
end
