class CreateSaleOrdersAndLogs < ActiveRecord::Migration[5.0]
  def change
    create_table :sale_orders do |t|
      t.boolean :paid
      t.text :notes

      t.timestamps
    end

    create_table :outbound_logs do |t|
      t.references :sale_order, null: false, foreign_key: true
      t.references :product, null: false, foreign_key: true
      t.integer :quantity, null: false

      t.timestamps
    end

    # The SaleOrder transition model's table generated by statesman:
    create_table :sale_order_transitions do |t|
      t.string :to_state, null: false
      t.jsonb :metadata, default: {}
      t.integer :sort_key, null: false
      t.integer :sale_order_id, null: false
      t.boolean :most_recent, null: false
      t.timestamps null: false
    end

    add_index :sale_order_transitions,
              [:sale_order_id, :sort_key],
              unique: true,
              name: "index_sale_order_transitions_parent_sort"

    add_index :sale_order_transitions,
              [:sale_order_id, :most_recent],
              unique: true,
              where: 'most_recent',
              name: "index_sale_order_transitions_parent_most_recent"
  end
end
